### ISSUE TITLE
Bug: Video element uses BGR instead of RGB.

### ISSUE THREAD

**Issue by phuang1024** [medilocus/graphic_videos#12]
**Describe the bug**
When adding a video element, the module exports it as BGR color instead of RGB.
That is, the red and blue channels are switched.

**To Reproduce**
1. Add a video element with distinguished blue and red colors
2. Expor the video

**Expected behavior**
The red and blue colors will be inverted.

**Screenshots**
![image](https://user-images.githubusercontent.com/64878874/107158006-2682e980-693c-11eb-9702-c10077cba253.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5
 - Version 1.0 Alpha

**Comment by phuang1024** [comment]
Error is in the file `graphics/elements/simple.py` line 376.

**Comment by ArjunSahlot** [comment]
Fixed #12
